import Navbar from "@/components/navbar";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={geistSans.className}>
        <main
          className="
        min-h-screen w-full
        bg-gradient-to-r from-red-500 via-yellow-500 to-cyan-400
        bg-[length:300%_300%]
        animate-aurora
        flex items-center justify-center
      "
        >
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
